### ISSUE TITLE
Dashing borders bug and stick to the move slots no matter what class I play

### ISSUE THREAD

**Issue by SSSiyan** [0ceal0t/JobBars#103]
Apologies if I missed this in an FAQ; I'm surprised I couldn't find an issue open for it already.
Most of the time this feature works beautifully (Other than a few interesting defaults that are easily swapped out), but sometimes I have this:

https://user-images.githubusercontent.com/58395132/141694387-72b628e7-f7e9-4dc4-b56d-faef0b7f91dc.mp4

I haven't figured out exactly what causes this yet, maybe something to do with leaving instances while still in combat or something?
This is fixed upon closing and opening the game, but obviously I'd rather not have to do that every time.
I'm happy to trial and error to try to figure out what's causing this if nobody knows, thank you in advance!

**Comment by 0ceal0t** [comment]
so in this specific example. Was the dashing border originally stuck when on samurai, or did you switch to samurai from some other job?

**Comment by 0ceal0t** [comment]
also, is there anything in your `dalamud.log`? (located in `%appdata%\XIVLauncher\`)

**Comment by SSSiyan** [comment]
Apolgies for the late reply, this doesn't happen too often so I was waiting for it to pop up again. It seems I can relatively often recreate it by removing enmity on a training dummy then mashing change class. I can confirm this has happened in an instance before though so I'm not sure what other circumstances could cause it

https://user-images.githubusercontent.com/58395132/141700995-60d778e5-c72f-4024-80d5-4beb8283fcf4.mp4

I can't see anything interesting in the log, just the

[JobBars] SWITCHED JOB TO DRG
[JobBars] SWITCHED JOB TO SAM
[JobBars] SWITCHED JOB TO DRG
[JobBars] SWITCHED JOB TO SAM

Not using any other hotbar stuff so I doubt anything's interfering. Hope you have luck in recreating it your end!

**Comment by AkazaRenn** [comment]
I had the same issue, all SAM monitors are turned off, still happened. Should be easy to recreate by switching to SAM, play whatever dungeon and see it happen.

**Comment by 0ceal0t** [comment]
should be fixed with the latest update. Can you try it and let me know if you're still having the issue?

**Comment by SSSiyan** [comment]
I smiled to myself when seeing "jobbars updated" when I signed in. I can no longer replicate this on a dummy, and just came out of my second synced run without any issues. Probably safe to say you got it! I'll bug you on this thread again if I see it. Thank you!!

**Comment by 0ceal0t** [comment]
Awesome! Let me know if it happens again
