### ISSUE TITLE
Feature Request: Additional gauge for Fisher

### ISSUE THREAD

**Issue by Nice2Meet-U** [0ceal0t/JobBars#104]
I'm not sure that you can do this for Fisher or other DoL. because this plugin is mostly for combat jobs.
But yeah. I have an idea about Fisher gauge and it would be good if you including this in JobBars too!
**why fisher? because fisher is the only jobs from DoL that have a buff timer**

### 1. Fish Hooked (~3s iirc)
![hooked](https://user-images.githubusercontent.com/72909567/142718115-417fb8e9-c6fa-46fc-9779-b0b480c09516.gif)
### 2. Proc Guage (Mooch II/Surface Slap/ Identical Cast 15s)
![mooch](https://user-images.githubusercontent.com/72909567/142718117-19d73aa8-168d-480e-804f-626f3a5c3b18.gif)
### 3. Patience Guage (P 60s / PII 145s)
![patience](https://user-images.githubusercontent.com/72909567/142718120-0b0bf9b0-5714-474d-a5e3-869350856495.gif)

**Comment by 0ceal0t** [comment]
after giving it some thought, going to limit the plugin to combat jobs for now, sorry
