### ISSUE TITLE
Endwalker Update

### ISSUE THREAD

**Issue by zocheez** [0ceal0t/JobBars#108]
Please update for Endwalker use, I can help test/code if you need/want it. Thank you for a great plugin.

**Comment by 0ceal0t** [comment]
the endwalker update likely won't be out for a while, since this is a very time of year for me

**Comment by zocheez** [comment]
Is there anything I can do to help, would you be willing to look over pull requests for updated items from your endwalker list to help move this along? I am a disabled developer so as such I have lots of free time to assist if you are willing.

**Comment by 0ceal0t** [comment]
sure, feel free to submit pull requests
