### ISSUE TITLE
Endwalker Support

### ISSUE THREAD

**Issue by Ozenuyu** [0ceal0t/JobBars#109]
Hello! Hope all is well.

I was wondering if there is a timeline or even interest in continuing this into Endwalker support?

OU

**Comment by 0ceal0t** [comment]
yes, it's just going to take some time because of my schedule

**Comment by 0ceal0t** [comment]
I don't have an exact timeline besides "it'll be done when it's ready"

**Comment by Ozenuyu** [comment]
I appreciate the response! Love the add on, and respect the amount of time it takes to do something like this. Was just curious since another of my favorite add - ons stated that they dropped the project.
