### ISSUE TITLE
Adapting DoT timer when sync (WHM)

### ISSUE THREAD

**Issue by Yorhu** [0ceal0t/JobBars#11]
Any chance to adapt the DoT bar for the WHM when you're synced to lvl 71 or below ?
Since the DoT (Aero) is 18 seconds long.

**Comment by 0ceal0t** [comment]
Fixed https://github.com/0ceal0t/JobBars/commit/f2fdbc09574b668e675d676a326f9eebfa14e738, will be in the next update
