### ISSUE TITLE
GCD timer only showing cast time for casters

### ISSUE THREAD

**Issue by nyxalteria** [0ceal0t/JobBars#114]
I was on RDM and the gcd cast timer for cursor only shows the actual cast time, not the full gcd timer like it did previously.

edit: did some further testing, smn also has the same problem, so does sage/whm/scholar (i assume it has to do with the reduced times that weren't reduced before with the other healers). it works fine with astro

**Comment by 0ceal0t** [comment]
seems to work fine for me. do you not have this behavior when setting the type to "GCD" and casting jolt?

https://user-images.githubusercontent.com/18051158/146126042-c1deacda-7071-4b87-9631-9d08e33f5c71.mp4

**Comment by nyxalteria** [comment]
its kind of harder to tell with jolt at any rate but here's an image of summoner for example 
![image](https://user-images.githubusercontent.com/92659516/146133160-dc02e99a-a073-4f55-ab47-3bf228ad3a08.png)
