### ISSUE TITLE
Limit break sound playing (seemingly at random)

### ISSUE THREAD

**Issue by Lumi92** [0ceal0t/JobBars#116]
Hey there,

I installed the new EW update for Jobbars and it seems to at random triggers (in combat and out), play the sound effect for a limit break going off.

I'm not 100% sure it's because of  jobbars, but it's the only plugin change I've made since yesterday.

Thanks for your time and the plugin!

**Comment by 0ceal0t** [comment]
it's the "gauge full" sound effect being triggered when you change jobs. You can turn it off by using the "Completion Sound Effect" settings in "Gauges"

**Comment by Lumi92** [comment]
Oh weird, I thought I disabled any completion noises for the jobs I  use.

I disabled it as you suggested, thanks again!
