### ISSUE TITLE
Suggestion for Ruin IV Stack Display

### ISSUE THREAD

**Issue by torakiti2017** [0ceal0t/JobBars#12]
Currently, the number of stacks is displayed in the buff column for Ruin IV stacks, but it is very difficult to see when there are multiple other buffs. If possible, I would be grateful if you could also display the UI dedicated to the number of Ruin IV stacks.

* In my local environment, I use Hojorin to force the stack to be displayed ... For reference of the image.
<img width="83" alt="smn0" src="https://user-images.githubusercontent.com/86459831/123428960-55ef7580-d601-11eb-84a2-f21f68b0c6d9.png">
<img width="96" alt="smn1" src="https://user-images.githubusercontent.com/86459831/123428967-5982fc80-d601-11eb-9a31-8feb47abacc9.png">
<img width="85" alt="smn3" src="https://user-images.githubusercontent.com/86459831/123428973-5be55680-d601-11eb-9a0d-9347cfcc5447.png">
<img width="90" alt="smn4" src="https://user-images.githubusercontent.com/86459831/123428976-5d168380-d601-11eb-89b9-d5acbb404a67.png">

**Comment by 0ceal0t** [comment]
added in https://github.com/0ceal0t/JobBars/commit/8219c64937a9017d58f7fd79106f29fb20c5b384, will be in the next update
