### ISSUE TITLE
Reaper Cooldown/Buff Tracking

### ISSUE THREAD

**Issue by Huskybix** [0ceal0t/JobBars#124]
Would it be possible to add additional tracking for reaper? In particular a way of tracking when Gluttony is off of cooldown as it has a 60s recast and whether you have the Soulsow buff up or not.

**Comment by 0ceal0t** [comment]
neither of these seem that useful, and would add more gauge bloat than I'm comfortable with. If other people request those two, I'll reconsider this, but I'll close it for now

**Comment by kaedys** [comment]
Soul Sow seems superfluous, but given how critical Gluttony is to the Reaper rotation, a tracker for the cooldown _would_ be handy.  There are a couple very critical rotational decisions that depend on the Gluttony CD.
