### ISSUE TITLE
GNB, PLD, SCH Mitigation - Raid Buff - Healer oGCD

### ISSUE THREAD

**Issue by ramondbc** [0ceal0t/JobBars#127]
- Add Heart of Stone/Coridium on GNB's Mitigation and Recitation on SCH's.
If possible, add Sheltron/Holy Sheltron on PLD's but show how much gauge it has instead of CD (If not, ignore this one).

- It would be nice if we could see Raid buff CDs and more Healer's oGCD. We already can track Star, Cosmos, Benediction, Liturgy and Pneuma that aren't mitigation.

- Option to show only cooldown instead of duration + cooldown when a skill is used.

**Comment by 0ceal0t** [comment]
added an option to add custom cooldown trackers
