### ISSUE TITLE
Suggestion: Reassemble Tracker

### ISSUE THREAD

**Issue by SharbySharby** [0ceal0t/JobBars#13]
Any way to enable abilities like Reassemble, Barrage, and Lance Charge to be tracked?

These are nice abilities to card as an Astro so it would be helpful.  :)

Awesome plugin by the way, thank you for your hard work! :D

**Comment by 0ceal0t** [comment]
added barrage and reassemble in https://github.com/0ceal0t/JobBars/commit/39609b1dfe4ada438d610dab44ec7ba9d14168cc, lance charge is already displayed as a buff. Those chances will be in the next update
