### ISSUE TITLE
[NINJA] Fleeting/Forked Raiju counter

### ISSUE THREAD

**Issue by vkyfox** [0ceal0t/JobBars#131]
Hello!
I've been using Jobbars since a week into Endwalker, and I'm loving it.

I think having a counter for Ninja's Fleeting and Forked Raiju would belong right in the tool's mindset, and personally would very much love to have that for myself.

What I think would be very cool is to have three diamonds, much like DRK's delirium; with diamonds filling up in one colour (let's say blue) with a sound as you get Fleeting Raiju stacks, then colouring up in another colour (purple for exemple) as you use Fleeting Raiju and gain a Forked Raiju stack, dissapearing after use (or loss) of the Fleeting Raiju.
I realise this might not be easy to implement as it's maybe not how the in-game HUD works, so I think a good compromise could be to have 6 stacks max and get them 2 by 2?

I hope this is possible! Anyway keep up the great work.

**Comment by vkyfox** [comment]
Well, today's patch removes the need for Fleeting becoming Forked, so we can settle for 3 diamonds.

**Comment by 0ceal0t** [comment]
added with latest update

**Comment by vkyfox** [comment]
Thanks so much ! Much love ❤️
