### ISSUE TITLE
Add GCD Gauge for casters

### ISSUE THREAD

**Issue by DenL** [0ceal0t/JobBars#132]
Hello, I can't speak for all casters as I only play some of them. But for those I played, there are instant cast GCD's that you do use to weave, and it helps to have a visual GCD indicator like physical jobs (especially to assist movement during GCD instant casts).

If you could add an optional (default off) GCD gauge for all jobs that would be great. Thank you!

**Comment by vkyfox** [comment]
I would very much agree with that, healers too, if possible. With GCD and cast not being related it can be nice to have a nice gauge to see it on top of the cursor circle!

**Comment by 0ceal0t** [comment]
done with latest update
