### ISSUE TITLE
Queue indicator for GCD gauge

### ISSUE THREAD

**Issue by DenL** [0ceal0t/JobBars#133]
Is it possible to add a queue indicator for the last .5 seconds of GCD gauge to indicate the queue window? 
example:
![image](https://user-images.githubusercontent.com/5632219/148101017-b0ca1c47-9cd9-4c75-9629-6a2e2ac72547.png)

Or perhaps in the style of SimpleTweaks' slidecast indicator:
![image](https://user-images.githubusercontent.com/5632219/148101182-8b3ca879-14d9-43b5-9bd0-1426666581b0.png)
![image](https://user-images.githubusercontent.com/5632219/148101233-a78e9376-f1f8-488f-9e39-7d9841104e88.png)

Thank you so much for your great work on this plugin!

**Comment by 0ceal0t** [comment]
added a while ago, forgot to update issue
