### ISSUE TITLE
[SAGE] Counter for Phlegma

### ISSUE THREAD

**Issue by vkyfox** [0ceal0t/JobBars#134]
Similar to machinist, I would love having a filling gauge for the two Phlegma stacks of Sage!

**Comment by 0ceal0t** [comment]
I'm a little hesitant to add this because Phelgma's cooldown isn't variable like machinists' (which are reduced when using hypercharge). However, considering sage doesn't really have any gauges currently, I'll look into it

**Comment by vkyfox** [comment]
That makes sense, I think it would be interesting because of the 45 seconds nature of Phlegma: you always want to keep it for raid buffs but have to dump it before it overcaps when it is not possible, and I find myself having a little of trouble to keep track of its charges with just the regular FFXIV cooldown indicator, especially during prog where I have a lot of things to keep track of and pay attention to. I think having a visual indicator would help tremendously in that regard. But I definitely understand that this is would not take top priority! :D

**Comment by 0ceal0t** [comment]
gonna close this for now, might revisit it later
