### ISSUE TITLE
Suggestion: search bar for custom cooldowns

### ISSUE THREAD

**Issue by nyxalteria** [0ceal0t/JobBars#136]
Currently you have to scroll through the huge list to find the skill you want to add a custom cooldown for. Its a massive pain because things are sorted badly in that list (likely game coding) so it would help if we could have a search bar for the icon/cooldown.

![image](https://user-images.githubusercontent.com/92659516/148635637-dddd3235-efe5-4ed3-9b4c-b4c305093f95.png)
Those two selections I mean. Trigger/icon

**Comment by AbooseYou** [comment]
You mean like this? you can already search for icons and tiggers
![SixcMJeoNe](https://user-images.githubusercontent.com/5286813/148635844-2074fbbf-3441-4aa3-ae91-9fb5bf9bc967.png)

**Comment by nyxalteria** [comment]
> You mean like this? you can already search for icons and tiggers ![SixcMJeoNe](https://user-images.githubusercontent.com/5286813/148635844-2074fbbf-3441-4aa3-ae91-9fb5bf9bc967.png)

is that  a testing update? mine looks like this lol 
![image](https://user-images.githubusercontent.com/92659516/148639785-8ec278c2-8fa6-433a-9657-c295e865d914.png)
