### ISSUE TITLE
More (in-game) sounds available for notifications?

### ISSUE THREAD

**Issue by jtabox** [0ceal0t/JobBars#137]
Gauges -> Settings -> Completion Sound Effect and Sound Effect

"Completion Sound Effect" has a much bigger selection of in-game sound effects than "Sound Effect", which only has the 16 usual sound effects you can use in macros with the "<se.X>" command. Trying to input a value higher than 16 for the second one changes the value to 16.

Would it be possible to extend "Sound Effect" choices to also include the Completion Sound Effects ones?

That because the 16 basic sound effects are used for macros, chat and other notifications, etc. So it's confusing to have an alert for Sound Effect go off and needing to check if it is an alert indeed. Moreover, not all 16 of them can be heard easily during combat so the pool to choose from is even smaller.

**Comment by 0ceal0t** [comment]
fixed a while ago, forgot to update issue
