### ISSUE TITLE
Feature Request: Add Riddle of Wind to Monk buffs

### ISSUE THREAD

**Issue by masanbol** [0ceal0t/JobBars#138]
Riddle of Wind is a new buff for Monk in Endwalker that I'd like to track alongside Riddle of Fire and Brotherhood.

**Comment by 0ceal0t** [comment]
imo, Riddle of Wind isn't an important enough buff to include in that section

**Comment by masanbol** [comment]
I would think that the option to include or not would be based on the type of skill or buff, not its "importance". There's lots of stuff included in this for various classes that track or show bars for non-critical or DPS-unrelated skills. Your choice I guess but seems odd to me
