### ISSUE TITLE
Plugin Dont see after Installation

### ISSUE THREAD

**Issue by snipfox85** [0ceal0t/JobBars#140]
Hi, after the intslla the plugin, and after a crash game (close with no error) , and reinstall again the plugin , i dont see a correct bar or other stuff from plugin.
ill try to delete local folder, but dont work-
Here a screen 
![no plugins](https://user-images.githubusercontent.com/97634327/149218464-8e359e8b-e68c-45e5-bb4c-1353e515cb94.png)

Hope can help me for fix that, TY in advance.

**Comment by 0ceal0t** [comment]
by default, the jobbars is attached to the hp/mp bar UI element. Since you have it hidden (probably so you can use DevlUI), it won't show up. You can either enable the hp/mp bar, or switch the UI element to the chatbox
