### ISSUE TITLE
Icon Replacement not working

### ISSUE THREAD

**Issue by kittlebug91** [0ceal0t/JobBars#147]
Last night it seemed to be working just fine across multiple jobs. However, booting it up this morning this feature seems to have been lost. The Gauge, Cooldown, and Buff bars are all functioning. I have tried restarting the game, uninstalling and reinstalling the plugin, and also rebooting my machine. Any insight would be appreciated, thanks!

**Comment by kittlebug91** [comment]
I've seen it begin working momentarily, but the fix doesn't last long. It does not seem to correspond to anything I'm doing to fix it.

**Comment by 0ceal0t** [comment]
for timers, it only shows the dashed border when they need to be reapplied (the DoT has fallen off). Does that also not work?

**Comment by kittlebug91** [comment]
Right. I'm having a lot of sporadic luck having it work. When the DoT is first applied, I have come to recognize the yellow circular timer indicator show up on them indicating it's duration, and then when the DoT would fall off, the dashed line would appear. Neither are happening.

I have also noticed that when the timer is working, the MP cost for DoTs (i.e. Biolysis) is not shown. My litmus test for seeing if this is working is seeing if the MP cost is listed on the icon. If it is absent, the timers are working. If it is present, none of the timer functions are working.

**Comment by kittlebug91** [comment]
While all of this is happening, the Buff dashed icons and text (Raging Strikes) is still working.

**Comment by kittlebug91** [comment]
Switch between HUD layouts also creates this error, which I think maybe connected because it's only happening to the DoTs? 
![image](https://user-images.githubusercontent.com/98613040/151637798-76131c0d-bc98-4dc7-9fe8-adcd7e566870.png)

**Comment by kittlebug91** [comment]
![image](https://user-images.githubusercontent.com/98613040/151637830-09a2b3bd-b460-4de5-a670-df326fe3e61f.png)

**Comment by kittlebug91** [comment]
The cooldown section--though Enabled--does not seem to show up either. :(

**Comment by kittlebug91** [comment]
This seems to have resolved itself today.
