### ISSUE TITLE
[Scholar] Chain Stratagem in Gauge (suggestion)

### ISSUE THREAD

**Issue by kittlebug91** [0ceal0t/JobBars#149]
Would it be possible to add Chain Stratagem to the Scholar Gauge like Excog is? It would be helpful to have this as part of the gauge, especially with the options to include a Completion Sound "When_Full" "When_Empty" etc to help see when it is ready to be used. Thanks for your consideration! :)

**Comment by 0ceal0t** [comment]
since this information is already readily available both in the ability icon and the "cooldowns" display, going to close this issue
