### ISSUE TITLE
Attach cooldown tracker with chatbox

### ISSUE THREAD

**Issue by Amarquier** [0ceal0t/JobBars#151]
Hello,

I'm trying to attach the cooldown tracker with the chatbox to be able to hide the party list as I'm using delvui.
However, the cooldowns are always attached to the HP/MP bars, whenever I select attach to chatbox or HP/MP.

Am I doing something wrong ?

**Comment by 0ceal0t** [comment]
fixed at some point, I forgot to update this issue
