### ISSUE TITLE
[Feature Request] Auto-attack timer for Cursor

### ISSUE THREAD

**Issue by haojunsui** [0ceal0t/JobBars#171]
An auto-attack timer that keep track of auto-attacks delay from currently equipped weapon 
![image](https://user-images.githubusercontent.com/6809863/170789593-256104d5-d973-484b-b339-f4cc9efad9c4.png)

**Comment by 0ceal0t** [comment]
probably not, since auto-attack timing isn't something you really need to know or keep track of
