### ISSUE TITLE
Sound Effect when dots run out plays even if turned off

### ISSUE THREAD

**Issue by Yuzumii** [0ceal0t/JobBars#18]
Had it a couple times now that the Sound Effect that is supposed to be turned off when set to 0, remains to be active on some classes and even after uninstalling the plugin.
This was only fixed after restarting the game.

**Comment by DiggityMan420** [comment]
i cant get the sound to play at all on NIN

**Comment by Yuzumii** [comment]
Apparently it wasnt your Plugin, turns out it was ACT that had a problem with the Cactpot Jobs Plugin, my apologies again. Forgot to close this post.

Keep up the great work guys.
