### ISSUE TITLE
Feature Request: GNB Dots

### ISSUE THREAD

**Issue by Chaotic-Sky** [0ceal0t/JobBars#189]
Unlike every other class ive noticed, Gunbreaker seems to be missing timers for its dots Sonic Break and Bow Shock. 
![image](https://user-images.githubusercontent.com/115907963/196014501-0750a6df-64dc-4e02-b96f-7780a27cbe96.png)

**Comment by 0ceal0t** [comment]
GNB DoTs aren't something you need to maintain, unlike those other ones. Outside of certain phase timings / cleave, you should just be pressing them on cooldown inside of a no mercy window. For that reason, I decided not to clutter the gauges with them.
