### ISSUE TITLE
Better options for bar placement

### ISSUE THREAD

**Issue by AwesomeJames2120** [0ceal0t/JobBars#19]
This plugin is fantastic, however making the placement of the bars look nice on every job is a challenge (at least on my hud setup) due to the lack of a Align Bottom option, and/or the ability to hold shift while dragging to snap the bars into place. Either of these additions would be greatly appreciated.

**Comment by 0ceal0t** [comment]
added position inputs in https://github.com/0ceal0t/JobBars/commit/28972497bc18b374075e557f86acca75b18da856, which should make precise positioning easier. I'll look into adding other positioning options as well

**Comment by 0ceal0t** [comment]
Snapping and alignment probably isn't going to happen, so I'll close this issue for now.

Hopefully the position inputs are enough. If you're still having trouble positioning things, feel free to open another issue.
