### ISSUE TITLE
Add Dot timer, Shadow Fang, NIN

### ISSUE THREAD

**Issue by Noshei** [0ceal0t/JobBars#20]
a bar for Shadow Fang dot for NIN would be nice to have.

**Comment by 0ceal0t** [comment]
I'll take a look at it, but that doesn't seem too useful to me, since shadow fang isn't refreshable. You just press it on cooldown, so knowing how much time it has left isn't important, unless I'm missing something

**Comment by Noshei** [comment]
oh, good point, I missed that it had a cooldown.
