### ISSUE TITLE
DRG Lance Charge/Dragon Sight GCD tracker

### ISSUE THREAD

**Issue by Spartanx9** [0ceal0t/JobBars#22]
Drg's trackers has 9 GCDs under LC/DS, which is impossible to hit if you're going any slower than 2.46. Since DRG is favored to go slower, can the gcd trackers be adjusted for 8 GCDs?

**Comment by 0ceal0t** [comment]
yep! thanks for letting me know

**Comment by 0ceal0t** [comment]
fixed https://github.com/0ceal0t/JobBars/commit/717071c1d939e8724cfe616f33c81832888d5b25. It'll be in the next update
