### ISSUE TITLE
When enable "Icon replacement enable", game start stuttering

### ISSUE THREAD

**Issue by Lornvene** [0ceal0t/JobBars#226]
After v1.3.1.0 update, whenever enable "Icon replacement enable" and engage in fight, game start stuttering and fps drop.
Disable it, game normal again

**Comment by MKhayle** [comment]
I can confirm reproducing this if XIVCombo (or a fork) is active

**Comment by Naab25** [comment]
Can frame rate goes from 70+ down to 6 fps in an alliance raid with  my viper when a combo plugin is active

**Comment by 0ceal0t** [comment]
does this still happen with v1.3.1.1?

**Comment by MKhayle** [comment]
Sounds like it's fixed with that update! No more issues on my end.
Thanks!
