### ISSUE TITLE
Icon Replacement Settings Revert

### ISSUE THREAD

**Issue by luxetumbra** [0ceal0t/JobBars#23]
When turned off, the icon replacement gets turned back on when logging out or sometimes when changing areas. This only seems to happen for specific classes, e.g. BLM's icon replacement always reverts back to on but SMN stays at what you set it. I have the global icon replacement unchecked.

**Comment by 0ceal0t** [comment]
fixed https://github.com/0ceal0t/JobBars/commit/717071c1d939e8724cfe616f33c81832888d5b25. It'll be in the next update
