### ISSUE TITLE
plugin just not working

### ISSUE THREAD

**Issue by friedpumpkin** [0ceal0t/JobBars#234]
not sure why but it just isnt working.

**Comment by Andreyf20** [comment]
Yep today's update completely broke the plugin nothing is working.

**Comment by friedpumpkin** [comment]
sadge. guess i make my bosses debuffs huge now for my dots.

**Comment by 0ceal0t** [comment]
[⁠known-issues](https://discord.com/channels/581875019861328007/1107127999335247942/1263300105747042377)⁠  JobBars got caught in the crossfire of this bugfix, so v1.3.1.2 has been disabled for now
should be back up an fixed tomorrow, ideally
