### ISSUE TITLE
Timers on job bars removed after update?

### ISSUE THREAD

**Issue by KaiJumpingway** [0ceal0t/JobBars#235]
The timers on cooldowns seem to be removed after the last update and is only the glowy border? The timer was the most valuable part of the information given by the party list cooldowns. If it was removed, please add this back
![image](https://github.com/user-attachments/assets/5eacc2f4-1e95-4d64-a903-f7f747536bbf)

How it used to be: 
![image](https://github.com/user-attachments/assets/fed88f85-4b8f-4283-9f23-7f7a01f305f3)
![image](https://github.com/user-attachments/assets/a3c5f11d-259a-4b13-a5ee-c41147d1d3e6)

**Comment by 0ceal0t** [comment]
same as https://github.com/0ceal0t/JobBars/issues/234
