### ISSUE TITLE
WAR Inner Release GCD counter does not count Inner Chaos and Chaotic Cyclone as valid GCDs

### ISSUE THREAD

**Issue by Snack-cat** [0ceal0t/JobBars#24]
When using Infuriate, the next of either Fell Cleave or Decimate gets upgraded to Inner Chaos and Chaotic Cyclone, respectively, and should be counted as a correct GCD during Inner Release.

**Comment by 0ceal0t** [comment]
This is intentional, since using inner chaos or chaotic cyclone is a huge dps loss, and is never optimal
