### ISSUE TITLE
Vertical gauges

### ISSUE THREAD

**Issue by TheGokki** [0ceal0t/JobBars#25]
Title. Would be nice to be able to have debuff bars to be vertical. And have this as a per-bar indivually.

**Comment by kaedys** [comment]
👍 to this.  I prefer a horizontally-centered HUD, and I'd love to have gauges I can orient vertically within that.  Horizontal gauges don't align well.

**Comment by 0ceal0t** [comment]
added in update 1.1.3.0 for bar gauges
