### ISSUE TITLE
Ability to change the order of proc trackers

### ISSUE THREAD

**Issue by AmberAvemour** [0ceal0t/JobBars#28]
For some jobs I (personally) use a different keybind layout than those that the existing proc trackers would make the most sense with, making drawing information from the additional trackers confusing at times. It's a good excuse to swap some of my binds around, but for some jobs like bard it's a bit tougher.

here's a quick example of a modified Dancer tracker

![dancerbar](https://user-images.githubusercontent.com/66646658/125767923-ec612dee-1021-4546-bbe1-081415d98d4a.png)

**Comment by 0ceal0t** [comment]
will be added in api4 update
