### ISSUE TITLE
Wyrm Wave and Scarlet Flame counters miss first WW/SF every time

### ISSUE THREAD

**Issue by MissXhiel** [0ceal0t/JobBars#3]
I can both see a WW/SF hitting the target in game, and the Aho's trigger for them counts the hit. However the counters for the plugin miss these every time.

**Comment by 0ceal0t** [comment]
Sorry I haven't been keeping up with issues. Is this still a problem?

**Comment by MissXhiel** [comment]
This is still an issue. It appears to be because of exactly how quickly we push out the first WW/SF when the rotation is working properly.

The trigger is still counting them, and I can see them hitting the target, it's just job bars that missing them.

**Comment by 0ceal0t** [comment]
latest update has changes to potentially fix this. I wasn't able to reproduce the original issue, so I can't say how effective the changes were. lmk if this is still an issue after the latest update (v1.0.0.9)

**Comment by MissXhiel** [comment]
This appears to be fixed in the latest release. Tested several times, even intentionally clipped both phoenix and bahamut on a dummy to see if it would catch a near-ghosted WW/SF and it does.

**Comment by 0ceal0t** [comment]
good to hear 👍
