### ISSUE TITLE
Buff Bar not going where u move it

### ISSUE THREAD

**Issue by DiggityMan420** [0ceal0t/JobBars#30]
Cant seem to move my buff Bars see [Pic](https://imgshare.io/image/phoIPP)

**Comment by DiggityMan420** [comment]
i noticed if i relog it fixes it but if you moving agian u need to relog not like the other bars they work fine

**Comment by 0ceal0t** [comment]
this is an interaction with the GP timer in SimpleTweaks. This should be fixed soon, but until then you can just disable that tweak and restart
