### ISSUE TITLE
not showing up at all

### ISSUE THREAD

**Issue by DiggityMan420** [0ceal0t/JobBars#33]
cant seem to get them to show at all see pics [1](https://imgshare.io/image/pcpDSl) [2](https://imgshare.io/image/pcpF8t)

**Comment by DiggityMan420** [comment]
if i click split gauges they show up but cant seen so move them correctly at all

**Comment by DiggityMan420** [comment]
and now i cant seem to get them back at all split or not

**Comment by 0ceal0t** [comment]
Are you using simpletweaks with the gp timer? There's a known bug with the timer that messes with JobBars

**Comment by DiggityMan420** [comment]
nope its off in simple tweaks

**Comment by 0ceal0t** [comment]
huh. Can you give me a full list of any other plugins you're using? Also could you send me your `dalamud.log` (it's in the `%appdata%\XIVLauncher\` folder) either here or through Discord? If the the file is too big, you can just delete it and start your game again and you'll have a fresh one.

**Comment by DiggityMan420** [comment]
[dalamud.log](https://file.io/bfY7cwFPFtwn)

**Comment by 0ceal0t** [comment]
can you try disabling the "show shield on hp bar" and "combo timer" simpletweaks if you have them enabled, then restarting?

**Comment by 0ceal0t** [comment]
also, what's the resolution of your monitor, and do you have multiple monitors? Do you also have "multi-monitor" windows enabled for Quicklauncher? Do you also have the 4k UI enabled?

**Comment by DiggityMan420** [comment]
ok  removed what you asked and restarted the game still nothing. So i removed simple tweaks all together and restarted still nothing. 1920x1080 yes 2 identical 120hz monitors. multi monitor enabled 4k ui yes

**Comment by 0ceal0t** [comment]
Ok, let's try this:
- Uninstall JobBars and close your game
- Delete `JobBars.json` inside of the `%AppData%\XIVLauncher\pluginConfigs` folder
- Go into `%AppData%/XIVLauncher` put the contents of this Zip file in there (there should be a .dll and a .json)
[Output.zip](https://github.com/0ceal0t/JobBars/files/6927251/Output.zip)

**Comment by DiggityMan420** [comment]
that worked can i ask if u would tell me what u changed

**Comment by DiggityMan420** [comment]
close this after u comment just like to know when u changed

**Comment by 0ceal0t** [comment]
Basically it was getting the position relative to both of your monitors for some reason, so I forced  it to only use the game's window.

Icon replacement is for DoTs, where the gcd timer on the skills icon is replaced with the time left on the DoT
