### ISSUE TITLE
No Mercy not showing up GNB

### ISSUE THREAD

**Issue by DiggityMan420** [0ceal0t/JobBars#37]
Tried all 3 types reloaded even cleared the json nope See Pics [1](https://imgshare.io/image/pJHIBH) [2](https://imgshare.io/image/pJHs7d) [3](https://imgshare.io/image/pJH8xf). Also i have never been able to get the the dot sound alarm to work no mater the number I pick. (Sound effect # when Dots are low)

**Comment by 0ceal0t** [comment]
Can you attach your log (`dalamud.log` in `%appdata%\XIVLauncher\`)?

**Comment by DiggityMan420** [comment]
my bad it works i was reading it wrong
u can close it
