### ISSUE TITLE
Option to invert gauge placement

### ISSUE THREAD

**Issue by TheTweets** [0ceal0t/JobBars#39]
Currently, gauges start at the top of the Gauge Bar window and cascade downward. This is perfect if you are placing the Gauge Bar window _below_ the official Job Gauge(s), but problematic if you wish to add gauges _above_ the Job Gauge.

For example, on Paladin, due to having 3 Gauge Bars, the window must be placed quite 'high' to ensure they do not overlap with the game's default Job Gauge, which is not a problem in and of itself. 
![image](https://user-images.githubusercontent.com/8594837/130393928-625b80b8-1f4b-4a8c-884c-477e67a224b1.png)

However, if one then swaps to another Job with few JobBar gauges (in this case, GNB), this causes the JobBar Gauge(s) to float unappealingly above the official Job Gauge
![image](https://user-images.githubusercontent.com/8594837/130394045-66219817-d603-4bb8-88d1-f6468ba8efa6.png)

I suspect this can be sidestepped in the interim using the Split Gauge feature, but this requires a lot of fiddling with positioning with each Gauge, making it non-ideal in the long term. The simplest way to resolve this problem would be to add an option for JobBar Gauges to cascade up from the bottom of the Gauge Bar window.

**Comment by 0ceal0t** [comment]
This is coming in the next update
