### ISSUE TITLE
SMN DoT Trackers do not update when using Tri-Disaster

### ISSUE THREAD

**Issue by MissXhiel** [0ceal0t/JobBars#4]
When refreshing DoTs via Tri-Disaster the trackers do not update.

Additionally, the CD effects on Miasma/Bio does not account for needing to start refreshing earlier than the duration of the DoT (even if they are purely visual effects).

**Comment by 0ceal0t** [comment]
Sorry I haven't been keeping up with issues. SMN DoT should now respect tri-disaster. Feel free to open another issue if this isn't the case for some reason
