### ISSUE TITLE
DoT icon keeps flashing when out of combat

### ISSUE THREAD

**Issue by AkazaRenn** [0ceal0t/JobBars#47]
![image](https://user-images.githubusercontent.com/8340896/131727020-919b027b-b448-49a6-839b-dd6916b47866.png)
Is it by design? I find it a bit frustrating that the icon keeps flashing when I'm not doing anything.

**Comment by 0ceal0t** [comment]
yes, this is intended. I'll add options to adjust it, however

**Comment by AkazaRenn** [comment]
@0ceal0t Thank you!

**Comment by AkazaRenn** [comment]
Oh, I just noticed it also flashes when I was targeting on my teammate. Would be nice to have it included in the change if possible, thanks again!

**Comment by AkazaRenn** [comment]
Hi there, just curious why this one is closed along with other issued, since it doesn't seem to be changed in 1.1.1.0, is it put back for Endwalker or something?

**Comment by 0ceal0t** [comment]
there are now options to change under what conditions the icon borders appear (including "Never"). You can also disable the icon replacement entirely
