### ISSUE TITLE
Issues with BRD DoT trackers + a request for a DoT tick tracker to be added

### ISSUE THREAD

**Issue by ShaeTsuPog** [0ceal0t/JobBars#5]
Bards DoT timer bars are very inaccurate. They start counting down immediately upon execution whereass the DoT doesn't, leading to the timer being about 2 seconds off the actual DoT time. 

They also do not reset when using Iron Jaws.

On top of this, I'd like to request a tick timer bar to be added. Tracking DoT tick timings is important in maximizing procs and a more accurate tracker than what is possible with triggers would be helpful, since they can desync easily.

**Comment by 0ceal0t** [comment]
Sorry I haven't been keeping up with issues. The BRD DoT trackers should be fixed, and now respect iron jaws. They should also be accurate to the actual DoT time (except for occasional rounding inconsistencies).

I'll looking into adding a DoT tick timer

**Comment by imynwulf** [comment]
This issue also appears to be affecting most other dots as well. 

Example: WHM applies Dia, tracker starts counting, impact damage and dot debuff show up, tracker resets. Tracker doesn't quite track with the debuff timer. 
![JobBar Dot Application error](https://user-images.githubusercontent.com/8398855/123493879-8a543900-d5e3-11eb-9642-7cbbc01f4de6.gif)

I've also noted similar reset behavior and time discrepancy issues with other dots as well.

**Comment by 0ceal0t** [comment]
the small stutter with DoT durations is fixed in https://github.com/0ceal0t/JobBars/commit/ceac66273a3aa36bd08c975285721fe90d5e39d3, will be in the next update
