### ISSUE TITLE
Suggestion for icon replacement: "Shadow Fang" style for DoT weaponskills/spells

### ISSUE THREAD

**Issue by AkazaRenn** [0ceal0t/JobBars#52]
Currently we are using normal CD styles:
![image](https://user-images.githubusercontent.com/8340896/132145752-4e90b67b-e2d5-4b6e-94fb-3ae719e33062.png)
GCD status will not be reflected onto it, making me a bit confused in battle. If we can replace it with the style of Shadow Fang (NIN 30 weapon skill with over 60s recast time):
![image](https://user-images.githubusercontent.com/8340896/132145828-2d214c5f-baf5-4d25-8ce8-7dd9376fb79a.png)
It would be much clearer.

**Comment by 0ceal0t** [comment]
will be added in next api4 update
