### ISSUE TITLE
Issue with job gauges (Dia) not showing up

### ISSUE THREAD

**Issue by Blueflamefirez** [0ceal0t/JobBars#57]
Hey, so i installed Job bars yesterday and it was working fine for a while, sometime in my game session i noticed that the bar for "Dia" was not showing up anymore. I can't pinpoint what the problem is as i have tried removing the plugin and it's config file and reinstalling to no avail. I have a couple of plugins installed + Ember overlay for spell timers (but it was working with ember overlay before disappearing).
Here is an image of the plugins i have installed.
![image](https://user-images.githubusercontent.com/16444831/134888391-74b0a332-6d55-45bd-8910-59fd3a072f87.png)

**Comment by Blueflamefirez** [comment]
And yes, i removed Job Bars before taking the screenshot for testing purposes

**Comment by 0ceal0t** [comment]
make sure that your HP/MP bar hud element is visible. This is a limitation of the current version of JobBars which will be fixed with the api4 update

**Comment by Blueflamefirez** [comment]
Okay it worked again, thank you! Do you have any idea of how far of we are of the api4 update?

**Comment by 0ceal0t** [comment]
the api4 release is planned for october 10th
