### ISSUE TITLE
Suggestion: Track DoTs via Focus Target

### ISSUE THREAD

**Issue by NoctisCepheus** [0ceal0t/JobBars#58]
Currently while playing WHM, I have a macro setup where Glare and Dia would cast on my target's target and automatically set it as a Focus Target. This way, I can keep selecting my party members without swapping back to the boss if I want to DPS. The problem is that the plugin only tracks DoTs if it is your current target. Otherwise, it would display 0.

There's a neat thing though where you can actually see the debuffs of your Focus Target. So what I ask is if it's possible that if the DoT data from the current target is not found, maybe it could try and check the Focus Target and get the data from there? It would really help a lot. I do hope it is possible.

**Comment by 0ceal0t** [comment]
the new version of jobbars pulls from the previously targeted enemy if you do not currently have one selected. I maybe look into adding a focus target option later
