### ISSUE TITLE
[Feature Request] Split Gauges on a Per Job Basis

### ISSUE THREAD

**Issue by someONEgood** [0ceal0t/JobBars#61]
**Thank you very much for this great plugin. I look forward to seeing your 6.0 implementations!**

I was wondering if it would be possible to make Split Gauges a per-job option?
I find that most of your gauges are spot on in positioning/spacing, but when I went to split them for a particular job that I wanted to tweak a bit, it split _all_ gauges across all the jobs While this is just a small inconvenience that just needed a bit of time to fix, it would be nice to see the option to only split gauges on specific jobs. Perhaps in the 6.0 implementation where it wouldn't be to obtrusive an update to those who already have their bars where they want them?

**Comment by 0ceal0t** [comment]
will be added in the next update
