### ISSUE TITLE
Suggestion for Icon Replacement: show dash border only when combo AND done/active

### ISSUE THREAD

**Issue by AkazaRenn** [0ceal0t/JobBars#64]
Take WAR's Strom's Eye for example, dash border comes when the buff expires, but to add it back, I still need to cast the full Heavy Swing - Maim - Storm's Eye combo. Maybe it's better to add an option to **only "Show Dash Border When Done/Active" and on combo at the same time**, so I won't be distracted to feel like "oh the buff is expired I just need to click this button to add it back since it has dash border", no it won't work.

Not sure if I'm being clear enough, let me know if you got questions!

**Comment by 0ceal0t** [comment]
That would make it very easy to let a DoT drop if you're only using the combo indicator as a gauge of when to use that skill. For example, if the DoT only had 1 second left when you got to the 3rd part of your combo, it wouldn't light up, and there would then be 3 more gcds where you don't have your DoT active.

I might add it as an option eventually, though

**Comment by 0ceal0t** [comment]
added https://github.com/0ceal0t/JobBars/commit/6c6d15b99f3550f7aa2ed165630acab23d3052b8 will be in the next update
