### ISSUE TITLE
Feature Request: GCD Bar

### ISSUE THREAD

**Issue by Noshei** [0ceal0t/JobBars#67]
Would be nice to have a bar to track the GCD, and if it gave an approximation of when you can queue your next ability that would also be amazing. This would be really useful on non casting jobs (and AST) so you dont have to look at the GCD circle on the icons.

Reposting this as I have now tried the mouse circle feature, and while it is nice it doesn't really fit with what I was wanting.  Would really like a bar, similar to the cast bar.

**Comment by 0ceal0t** [comment]
added in update 1.1.3.0
