### ISSUE TITLE
Hide outside of GCD window

### ISSUE THREAD

**Issue by gucciBane** [0ceal0t/JobBars#7]
Sorry if this is an option that I'm not finding, but it would be great if we could hide the 'within GCD' bars (ex. WAR's Inner Release) when they're not relevant, like when IR isn't running.

Awesome plugin.

**Comment by 0ceal0t** [comment]
Added in https://github.com/0ceal0t/JobBars/commit/d5de89d1c93d98401bb0f0b8ab4cf3683807e232, will be in the next update
