### ISSUE TITLE
Add tank specyfic spells to Cooldowns to show on party listy + interrupts and stuns

### ISSUE THREAD

**Issue by Barley194** [0ceal0t/JobBars#70]
I'm talking Rampart, the 30% mitigation spell (Sentinel for e.q.), interrupts like Interject and stuns like Low Bow for all classes.

That would be huge!

**Comment by 0ceal0t** [comment]
I might add the 30% cds (shadow wall, etc.), but probably not interrupts and stuns, since their cooldown is very low, and they are almost never necessary

**Comment by ShinjukuCurry** [comment]
@0ceal0t Piggybacking off this thread since it's relevant, could you consider adding raid buffs like Trick Attack, Chain Stratagem into the cooldowns section too? I know you can track it by the buff bar, but it would be great if I can have their cooldown info next to the party members so I know if they're using it on time and when it comes up.

**Comment by 0ceal0t** [comment]
I'm trying to keep the cooldowns section dedicated to mitigation, but I may reconsider that if there's enough demand for it

**Comment by Platapoop** [comment]
Would also like seeing defensive cooldowns like rampart and sentinel!

**Comment by owatan** [comment]
Hi, I found this nice plugin and extended the functionality for myself to try it out; https://github.com/owatan/JobBars/commit/b797b839adf0243d0ee967a2a2acf40bdfdf38bb.
![image](https://user-images.githubusercontent.com/2733827/146628414-c0c3b185-8620-40d5-adc9-45bcc7852edb.png)

This plugin allows users to choose to show or hide each skill, so I think it should be possible to select all the ones that can be acquired. If you will merge my pull requests, I will add all the actions myself.

and ... this plugins is only a maximum of five will be displayed. Could you expand this to more than 10? Let me know where it is defined and I'll edit it myself.

**Comment by BWalrus** [comment]
> Hi, I found this nice plugin and extended the functionality for myself to try it out; [owatan@b797b83](https://github.com/owatan/JobBars/commit/b797b839adf0243d0ee967a2a2acf40bdfdf38bb). ![image](https://user-images.githubusercontent.com/2733827/146628414-c0c3b185-8620-40d5-adc9-45bcc7852edb.png)
> 
> This plugin allows users to choose to show or hide each skill, so I think it should be possible to select all the ones that can be acquired. If you will merge my pull requests, I will add all the actions myself.
> 
> ~and ... this plugins is only a maximum of five will be displayed. Could you expand this to more than 10? Let me know where it is defined and I'll edit it myself.~ → I found it defined here.
> 
> https://github.com/0ceal0t/JobBars/blob/b0303f19ee0f1173685456d87fd2b28b7e897aba/JobBars/UI/Cooldown/UICooldown.cs#L129

Is there a way I can download your version? I want to see the extra tank cooldowns too but I'm not familiar with how Github works.

**Comment by owatan** [comment]
> Is there a way I can download your version? I want to see the extra tank cooldowns too but I'm not familiar with how Github works.

I'm sorry to induce to my repository via original version's issues, my versions can download here:
https://github.com/owatan/JobBars/releases/tag/1.2.0.3

Pay respect to 0ceal0t-san who developed original version's JobBars.

**Comment by 0ceal0t** [comment]
added an option to add custom cooldown trackers. Gonna close this for now, but feel free to comment if I missed any use cases
