### ISSUE TITLE
Icon Replacement: BLM Thunder III/IV

### ISSUE THREAD

**Issue by AkazaRenn** [0ceal0t/JobBars#72]
The effects of Thunder III and Thunder IV are mutually exclusive to each other, wondering if it could be reflected on icons, maybe show the "cool down effect" on both icons for either DoT.

**Comment by 0ceal0t** [comment]
kind of annoying on the tech side since they have different durations and stuff. For now, I think leaving it up to a user to know how the DoT interact and which one is currently applied is reasonable.

Might get around to this at some point in the future
