### ISSUE TITLE
Feature Request: reverse fill order for gauges tracking stacks and charges

### ISSUE THREAD

**Issue by kaedys** [0ceal0t/JobBars#74]
Currently, gauges that track stacks (ex. Atonement) or charges (ex. Ricochet) exclusively fill left-to-right, and I'd really like to reverse the fill order for some of them.  For example, if I have my Ricochet bar on one side of my HUD and my Gauss Round bar on the other, it's a bit disorienting to have them both fill left-to-right.  If I could reverse them, I could have them fill either outside-to-inside or inside-to-outside, relative to the center of my screen. Ultimate point is similar to (but in addition to) the vertical gauge feature in another issue out here.  I like to have a horizontally-centered "HUD" type configuration, So having everything on a left-to-right plane is an issue (hence the vertical gauges) and also not being able to mirror elements is problematic.

----

As a stretch request on it, could also be an alternative display type where, rather than showing all of the slots all of the time, it would only show filled ones, with them being left-aligned, right-aligned, or center-aligned.  So, for example for Atonement, it would show 3 filled in the same way it currently does, but when you use one, it would show only 2 diamonds total (both filled), rather than 2 filled and 1 empty, and if center-aligned were selected, they would be repositioned so the gap between the two was where the center of the middle one used to be when at 3.

```
◆ ◆ ◆
 ◆ ◆
  ◆
```
Versus the current behavior:
```
◆ ◆ ◆
◆ ◆ ◇
◆ ◇ ◇
```

The former obviously aligns a bit more cleanly with a centered positioning style.

----

Related, and effectively included in the above, but could also be implemented entirely separately if you decide not to do the above stretch request: an option for gauges that track stacks to hide when empty, similar to the GCD option to hide when inactive.  This one maybe should be an option on each individual stack entry, though, instead of a single global.

Oh, and something entirely unrelated, the sound effect for DoTs being low will only play if the DoT gauge is shown, but I don't generally use the DoT gauges (I have another plugin that displays them as icons instead).  Could an option be added to play sound effects even if the gauge for that DoT is hidden?  I've worked around this currently by setting the scaling for those gauges to 0 (which makes them very very small, but not actually disappear), and placing them in a corner of the screen, but it'd be nice to not have to use that workaround.  Obviously lower priority, though, given that there _is_ a workaround, and it's serviceable, if a bit hacky.

**Comment by 0ceal0t** [comment]
reverse fill order added in update 1.1.3.0
