### ISSUE TITLE
Buff Bar Resize + animated gauge

### ISSUE THREAD

**Issue by rsigim** [0ceal0t/JobBars#8]
If possible make the buff bar resizable to be a single line with all buffs

Also, is possible to make the gauge animated when filling? mimiking the ingame simplified one

**Comment by 0ceal0t** [comment]
Added # of buffs per line option in https://github.com/0ceal0t/JobBars/commit/d5de89d1c93d98401bb0f0b8ab4cf3683807e232, so it'll be in the next update

Animations might be possible, but it would take some larger restructuring, so probably won't happen soon

**Comment by 0ceal0t** [comment]
added limited animations in https://github.com/0ceal0t/JobBars/commit/b857b5d2a82ed97dde0196dd6979d617efc92287
