### ISSUE TITLE
[BUG] Inner Release Cooldown showing on other abilties/slots

### ISSUE THREAD

**Issue by someONEgood** [0ceal0t/JobBars#87]
**As usual, much much gratitude for this amazing plugin.** 👍 

As a preface, this issue was present before the 1.1.2.0 and 1.1.2.1 hotfix updates (and still persists), but I'm just now getting around to posting the issue. So it wasn't anything that those patches introduced.

The issue is that, at least on cross-bars, when using inner release, it also puts the cooldown timer on the RT+Y (R1 + Triangle) slot. In this particular case, on Crossbar-8 (if that matters). I noticed it on Low Blow and Reprisal on separate  LT+RT and RT+LT configs as seen in this gif:
![wlOalWCZlF](https://user-images.githubusercontent.com/46905309/138617803-2df521be-dd0b-44b9-ac6f-e3402d306d7a.gif)

Just to make sure it wasn't limited to role actions, I tested it with Storm's path in that slot as well, and the issue still occured, so I'm inclined to believe it's slot related? If you need any additional info or vids or screen sharing to help reproduce the issue, just lemme know. Thank you again.

**Comment by someONEgood** [comment]
Sorry to necro this closed thread, especially when the bug was deemed fixed, but I'm still having the same issue.
The issue on Warrior still persists, as well as on PLD:


https://user-images.githubusercontent.com/46905309/139735312-78e614e5-fc4f-46bf-b7d5-cf81b8f681a0.mp4

It would seem that the cooldown timer is being overlaid on it's "sister" slot on the face-buttons.
So for instance as you see on the WAR cooldown on the initial bug report, RT+D-Pad UP gets placed on RT+Y, whereas here on PLD, RT+D-Pad RIGHT gets placed on RT+B.

Of further interest is that this only occurs on "Expanded Hold Controls" bars: LT -> RT and RT -> LT.
Here's an example: 

https://user-images.githubusercontent.com/46905309/139736079-016326fb-d943-4968-aa8f-191242ec6317.mp4

As you can see it doesn't occur on the main bar, but does on Expanded, even if the CD was triggered on the main bar.
Perhaps this is an issue with having duplicate abilities, or just an issue with Expanded Hold Controls?

Hopefully this helps to narrow down this elusive bug. If there's any additional information I can provide, please let me know.
 **Really appreciate your time and effort. Thank you 0ceal0t.**

**Comment by 0ceal0t** [comment]
should be fixed in 1.1.2.3

**Comment by someONEgood** [comment]
I been looking forward to this all day! Just managed to test this out, and while it appears LT-->RT is still being a bit stubborn (with the timer not appearing _at all_), I can confirm that the misplaced timers are now appearing in the correct location on Main Bar and Expanded Hold RT-->LT. Nice work! Thank you!!


https://user-images.githubusercontent.com/46905309/140232868-273dfc31-661a-4214-ad2d-e89ba99b45ac.mp4

**Comment by 0ceal0t** [comment]
dang, I really thought I covered all of the edge cases. Re-opening again 😭

**Comment by someONEgood** [comment]
I know my dude! I'm sorry!
I _really_ didn't wanna be the messenger (_again_ 😬)on this one lol.
But I wanted you to at least be aware of the issue.
(DM me if you want me to run any test builds, I'm more than happy to help).

**Most importantly I also want to really wanna drive home that your work and time spent are very appreciated.
**THANK YOU.****

**Comment by 0ceal0t** [comment]
should be fixed (hopefully for good) with update 1.1.3.0. Can you test it and let me know if everything is working as expected?

**Comment by someONEgood** [comment]
~~WE~~ **YOU DID IT!** ~~WE~~ **YOU DID IT!** ~~WE~~ **YOU DID IT! YAY!**

https://user-images.githubusercontent.com/46905309/140747720-3cefe914-7c3a-4a2f-9585-b8399c23ed22.mp4

**THANK YOU!**
