### ISSUE TITLE
Feature Request: Customizing the position of the cursor rings

### ISSUE THREAD

**Issue by Nitpicky** [0ceal0t/JobBars#88]
As a controller player, the usage of the cursors feature is not very intuitive, and putting it in the middle is not very convenient either. So having the ability to place it wherever we want could help, plus we could do fancy things like this:
![GNB](https://user-images.githubusercontent.com/93129334/138684110-6f9e6585-7632-49a2-ae80-c1927a3cd14f.png)
In hope you could look into that.

**Comment by 0ceal0t** [comment]
added an option to specify a custom position. right now it's global across all jobs, I'll look into making it a per-job option later
