### ISSUE TITLE
Feature Request (possibly also bug?): Persist sound-related settings between updates and add an option to disable all sound meddling

### ISSUE THREAD

**Issue by daria-mianne** [0ceal0t/JobBars#89]
Possible bug portion:

Multiple updates have reset my settings, causing sounds that I vigorously do not want to be re-enabled. These sounds take several minutes to re-disable as well, since they can only be disabled by going through all the abilities one-by-one and uncheck all the "Play sound when..." boxes _and_ change all the "Completion sound" dropdowns to never. These settings should persist between updates.

Feature request portion:

Please add a checkbox - probably in the Settings section of the configuration - to allow one-click disabling of all sound meddling done by the plugin. The sounds are obtrusive and confusing, particularly on classes that have a lot of them. I've typically spent the proc or refreshed the dot that the sounds are for before they actually play, anyway, and this makes them even more confusing, as they still play in that case. For example, with Bard's proc that resets the Bloodletter cooldown, most of the time I've seen the proc and queued the BL before the sound plays.

**Comment by 0ceal0t** [comment]
Some updates will cause some settings to get wiped. It's part of the process, and trying to reconcile dozens of different possible configurations is a huge pain.

As far as disabling sound effects, there is now a setting labeled "Completion Sound Effect". Set that and  the one labeled "Sound Effect #" to zero if you don't want any sound effects.
