### ISSUE TITLE
Suggestion for CD overlay on DoTs

### ISSUE THREAD

**Issue by MissXhiel** [0ceal0t/JobBars#9]
I noticed this on SMN, so I'm not sure if this is the case for all DoTs, but the overlay that implies the skill is "on CD" (even if we can press it again no matter what) is equal to the duration of the DoTs, which may cause some to refresh after the DoTs fall off.

SMN starts hard cast refresh at ~6 seconds on DoTs. Unsure how this will impact other classes.

Side note: Leaving it at 6 seconds is probably best, because refresh time using Tri-D has 1001 exceptions.

**Comment by 0ceal0t** [comment]
Good point, but I'll probably leave it just in the interest of not causing confusion. I may add an option for that in the future.

**Comment by PuckAlive** [comment]
Customizable "Delay Offset" that shaves time off the top so it starts the DoT countdown at (for instance) 24s

**Comment by AkazaRenn** [comment]
Would like to have the "delay offset" for icon replacement, too. It would be helpful to remind me of casting DoT's at the correct timeslot.

**Comment by 0ceal0t** [comment]
added https://github.com/0ceal0t/JobBars/commit/6c6d15b99f3550f7aa2ed165630acab23d3052b8 will be in the next update
