### ISSUE TITLE
Job gauge does not advance   

### ISSUE THREAD

**Issue by AngelSeed** [0ceal0t/JobBars#94]
The gauge does not advance even with the Diamond style of JobBars.
I've tried a few others, but I feel that only Diamond isn't working.
This symptom appeared after V1.1.2.2.
It was the same for every job.
arrow and bar are normal. I like Diamond.
I would appreciate it if you could take any action.
https://www.twitch.tv/videos/1193632038

**Comment by 0ceal0t** [comment]
should be fixed in v1.1.2.3
