### ISSUE TITLE
Feature Request: Form indicator for Monk

### ISSUE THREAD

**Issue by kaedys** [0ceal0t/JobBars#95]
I'd like a cleaner way to track what form I'm in as a Monk, and I thought that the JobBars diamond gauge would actually work pretty well for it.  Since the forms proceed in a well-ordered sequence (opo-opo -> raptor -> coeurl), I figured a 3-diamond indicator that has each of the diamonds allocated to one of the 3 forms (order probably should default to the above, but probably should be configurable in the same way the order of the various proc indicators are).  As you cycle through the forms, the diamonds would light up in sequence, so you could at-a-glance tell which form you're in and which set of abilities you should be looking at using next after a rotation disruption.

**Comment by 0ceal0t** [comment]
after giving it some thought, I decided that this isn't that useful. There are already plenty of indicators in-game for what form you're in and what abilities you can use, and I think this would just add more clutter
