### ISSUE TITLE
Feature Request: An easier way to test sound effects

### ISSUE THREAD

**Issue by AkiraChisaka** [0ceal0t/JobBars#96]
Currently the completion sound effect doesn't seem to be the in game macro sound effects (e.g. <se.1>, <se.2>).

It's seems to be a different order of system sound effects.

It's really hard to trigger them to find one I need.

I hope if possible, add a button beside the sound effect settings to test the sounds.

**Comment by 0ceal0t** [comment]
added in update 1.1.3.0

**Comment by AkiraChisaka** [comment]
Thank you so much ocealot!
