### ISSUE TITLE
Feature Request: MP Bars for BLM and Healers

### ISSUE THREAD

**Issue by DenL** [0ceal0t/JobBars#97]
Really like the MP bar that DRK have, allows me to easily set up a nice hud. Could we get the same thing (minus the 3000mp chunk indicators) for BLM and healers as they also need to monitor MP?

Thanks!

**Comment by 0ceal0t** [comment]
probably not, since the default MP already works fine for those jobs. There's not really any additional information that could be added like with DRK

**Comment by DenL** [comment]
Just want to make a case for something like it. While there are tweaks that let you separate MP from the HP and lay it out the way you want, you cannot set it up by job (e.g. mp bar in a different place based on what job you're on). With JobBars we'd be able to do that.
Also with BLM you can set up ticks for the cost of a Fire 1 for instance.

**Comment by 0ceal0t** [comment]
ok, that makes sense

**Comment by 0ceal0t** [comment]
added in update 1.1.3.0
