### ISSUE TITLE
Sound effects not working for DoT

### ISSUE THREAD

**Issue by YuleXiv** [0ceal0t/JobBars#98]
I hear sounds for procs but not for DoT timers about to expire.

**Comment by 0ceal0t** [comment]
Do you have the settings something like this? Also is this for all DoTs?

![image](https://user-images.githubusercontent.com/18051158/140659218-f839afd9-d2f0-4f2a-94b3-09c53261f4ed.png)

**Comment by YuleXiv** [comment]
fixed it, ty for the screenshot, for some reason the sound effect # was set to 0 (i didnt change it but mustve loaded like that after an update)
